import type { Metadata } from "next";
import { Red_Hat_Display } from "next/font/google";
import AppWrapper from "../wrappers/app-wrapper";
import "../assets/globals.css";

const redHatDisplay = Red_Hat_Display({
  variable: "--font-red-hat-display",
  weight: ["300", "400", "500", "700", "900"],
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: never;
}>) {
  return (
    <html lang="en" className="w-full h-full">
      <body
        className={`${redHatDisplay.className}  ${redHatDisplay.variable} antialiased w-full h-full`}
      >
        <AppWrapper session={session}>{children}</AppWrapper>
      </body>
    </html>
  );
}
